name: my workflow
on: [push]

jobs:
  build:
    name: hello github action
    runs-on: ubuntu-18.04
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      
      - name: echo Hello
<<<<<<< HEAD
        run: echo "Hello"
=======
        run: echo "Hello"
>>>>>>> eb326c856c067ce782e6b4d5244b5c8fe448b353
