name: my workflow
on: [push]

jobs:
  build:
    name: hello github action
    runs-on: ubuntu-18.04
    steps:
      - name: chaeckout source code
        uses: actions/checkout@master
      
      - name: echo Hello
        uses: echo "Hello"